# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - polarix_arm_controller
    - hand_controller

  polarix_arm_controller:
    type: FollowJointTrajectory
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_roll
      - wrist_pitch
    action_ns: follow_joint_trajectory
    default: true
  hand_controller:
    type: GripperCommand
    joints:
      - finger_joint_left
      - finger_j1
    action_ns: gripper_cmd
    default: true