# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    polarix_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

polarix_arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_roll
      - wrist_pitch
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    joints:
      - finger_joint_left
      - finger_j1
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity